### ISSUE TITLE
post sobre checklist de ajuda sobre os robôs

### ISSUE THREAD

**Issue by Andrelamor** [automatiza-mg/automatizacoes#70]
## ações 
- [x] postar versão inicial em _draft_ (Arquivo-mãe acessível [aqui](https://github.com/automatiza-mg/automatizacoes/blob/main/docs/blog/posts/20240118_checklist_ajuda_robos/index.md))
- [ ] checar se listagem de erros atende o propósito (o principal está listado aqui neste rascunho? tem item que não vale estar neste post?) @YanVieira1905 @IsaRomancini @gabrielbdornas 
- [ ] colar figuras (alternativa de pesar menos? navegabilidade?)
- [ ] revisar texto

**OBS**.: ideia originalmente registrada no repo da imersão SCAP](https://github.com/automatiza-mg/imersao-scap/issues/4#issuecomment-1885477148), mas é aplicável a qualquer robô que estiver no site; então vou fazer uma sugestão de post e deixá-lo em modo rascunho (draft - visível localmente) partir deste issue:
![image](https://github.com/automatiza-mg/automatizacoes/assets/52294411/53908b8b-32ef-439e-91b5-5c8cd5b89fcf)

**Comment by gabrielbdornas** [comment]
@Andrelamor e @YanVieira1905 quando entrei nesse Issue vi que ele não estava vinculado a nenhum projeto. Todos os repositórios de nossa organização tem um [Action](https://github.com/automatiza-mg/automatizacoes/blob/main/.github/workflows/add_project_to_issue.yml) configurado para tal, mas como tudo na vida, ele pode falhar. Peço que vocês observem sempre que um Issue for criado se ele foi vinculado ao nosso projeto. Isso vai garantir que não percamos nenhum Issue em nossa lista de atividades.
